<?php
declare(strict_types=1);
use WHMCS\Database\Capsule;
function radiussphere_MetaData(): array{return ['DisplayName'=>'RadiusSphere','APIVersion'=>'1.1','RequiresServer'=>false,'ListAccountsUniqueIdentifierDisplayName'=>'RADIUS username','ListAccountsUniqueIdentifierField'=>'username'];}
function radiussphere_ConfigOptions(): array{return ['Cluster ID'=>['Type'=>'text','Size'=>'8','Description'=>'RadiusSphere cluster ID.'],'Policy ID'=>['Type'=>'text','Size'=>'8','Description'=>'RadiusSphere policy ID.'],'Identity realm'=>['Type'=>'text','Size'=>'32','Default'=>'','Description'=>'Optional realm appended by the configured identity strategy.']];}
function radiussphere_CreateAccount(array $p): string{return radiussphere_command($p,'provision');}
function radiussphere_SuspendAccount(array $p): string{return radiussphere_command($p,'suspend');}
function radiussphere_UnsuspendAccount(array $p): string{return radiussphere_command($p,'unsuspend');}
function radiussphere_TerminateAccount(array $p): string{return radiussphere_command($p,'terminate');}
function radiussphere_ChangePassword(array $p): string{return radiussphere_command($p,'rotate_credential');}
function radiussphere_ChangePackage(array $p): string{return radiussphere_command($p,'change_policy');}
function radiussphere_TestConnection(array $p): array{try{foreach(['mod_radiussphere_clusters','mod_radiussphere_policies','mod_radiussphere_commands'] as $t)if(!Capsule::schema()->hasTable($t))throw new RuntimeException('RadiusSphere addon is not activated.');$cluster=(int)radiussphere_option($p,'Cluster ID');if(!Capsule::table('mod_radiussphere_clusters')->where('id',$cluster)->exists())throw new RuntimeException('Configured cluster does not exist.');return ['success'=>true,'error'=>''];}catch(Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];}}
function radiussphere_ClientArea(array $p): array{try{$link=Capsule::table('mod_radiussphere_service_links')->where('service_id',(int)$p['serviceid'])->first();return ['templatefile'=>'clientarea','vars'=>['configured'=>(bool)$link,'username'=>(string)($p['username']??''),'state'=>$link?'Managed by RadiusSphere':'Awaiting provisioning']];}catch(Throwable $e){return ['templatefile'=>'clientarea','vars'=>['configured'=>false,'state'=>'Status unavailable']];}}
function radiussphere_command(array $p,string $type): string{try{foreach(['mod_radiussphere_clusters','mod_radiussphere_policies','mod_radiussphere_identities','mod_radiussphere_commands'] as $t)if(!Capsule::schema()->hasTable($t))throw new RuntimeException('RadiusSphere addon is not activated.');$cluster=(int)radiussphere_option($p,'Cluster ID');$policy=(int)radiussphere_option($p,'Policy ID');$username=trim((string)($p['username']??''));if($cluster<1||$policy<1||$username==='')throw new RuntimeException('Cluster ID, Policy ID, and service username are required.');if(!Capsule::table('mod_radiussphere_clusters')->where('id',$cluster)->where('maintenance',false)->exists())throw new RuntimeException('Cluster is unavailable or in maintenance.');if(!Capsule::table('mod_radiussphere_policies')->where('id',$policy)->where('enabled',true)->exists())throw new RuntimeException('Policy is unavailable.');$identity=Capsule::table('mod_radiussphere_identities')->where(['cluster_id'=>$cluster,'username'=>$username])->first();if(!$identity){$id=Capsule::table('mod_radiussphere_identities')->insertGetId(['cluster_id'=>$cluster,'username'=>$username,'realm'=>radiussphere_option($p,'Identity realm'),'state'=>'active','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);$identity=(object)['id'=>$id];}$revision=(int)Capsule::table('mod_radiussphere_policies')->where('id',$policy)->value('current_revision');Capsule::table('mod_radiussphere_service_links')->updateOrInsert(['service_id'=>(int)$p['serviceid']],['identity_id'=>$identity->id,'policy_id'=>$policy,'policy_revision'=>$revision,'updated_at'=>date('Y-m-d H:i:s'),'created_at'=>date('Y-m-d H:i:s')]);$key=hash('sha256',$type.'|'.$p['serviceid'].'|'.$cluster.'|'.$policy.'|'.$revision.'|'.$username);Capsule::table('mod_radiussphere_commands')->insertOrIgnore(['idempotency_key'=>$key,'cluster_id'=>$cluster,'service_id'=>(int)$p['serviceid'],'type'=>$type,'payload'=>json_encode(['identity_id'=>$identity->id,'username'=>$username,'policy_id'=>$policy,'policy_revision'=>$revision]),'state'=>'pending','available_at'=>date('Y-m-d H:i:s'),'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);logModuleCall('radiussphere',$type,['serviceid'=>$p['serviceid'],'username'=>$username,'cluster'=>$cluster,'policy'=>$policy],'queued','success',[(string)($p['password']??'')]);return 'success';}catch(Throwable $e){return 'RadiusSphere error: '.$e->getMessage();}}
function radiussphere_option(array $p,string $n): string{return trim((string)($p['configoptions'][$n]??''));}
