<?php
declare(strict_types=1);
use WHMCS\Database\Capsule;

const RADIUSSPHERE_VERSION = '0.1.0';

function radiussphere_config(): array { return ['name'=>'RadiusSphere','description'=>'Enterprise FreeRADIUS control plane for WHMCS.','version'=>RADIUSSPHERE_VERSION,'author'=>'ServerSpan','fields'=>['command_mode'=>['FriendlyName'=>'Provisioning mode','Type'=>'dropdown','Options'=>'synchronous,outbox','Default'=>'outbox','Description'=>'Outbox is recommended for resilient backend operations.'],'audit_retention_days'=>['FriendlyName'=>'Audit retention days','Type'=>'text','Size'=>'6','Default'=>'365'],'usage_retention_days'=>['FriendlyName'=>'Usage retention days','Type'=>'text','Size'=>'6','Default'=>'365'],'allow_session_disconnect'=>['FriendlyName'=>'Enable session disconnect','Type'=>'yesno','Description'=>'Allows supported drivers to terminate live sessions.']]]; }
function radiussphere_activate(): array { try { $s=Capsule::schema(); if(!$s->hasTable('mod_radiussphere_clusters')) { $s->create('mod_radiussphere_clusters',function($t){$t->increments('id');$t->string('name',100)->unique();$t->string('driver',40);$t->string('endpoint',255);$t->text('credentials_encrypted')->nullable();$t->string('status',20)->default('unknown');$t->boolean('maintenance')->default(false);$t->timestamp('last_health_check')->nullable();$t->timestamps();}); $s->create('mod_radiussphere_policies',function($t){$t->increments('id');$t->string('name',100)->unique();$t->text('description')->nullable();$t->integer('current_revision')->unsigned()->default(1);$t->boolean('enabled')->default(true);$t->timestamps();}); $s->create('mod_radiussphere_policy_revisions',function($t){$t->increments('id');$t->integer('policy_id')->unsigned();$t->integer('revision')->unsigned();$t->json('rules');$t->integer('created_by')->unsigned()->nullable();$t->timestamps();$t->unique(['policy_id','revision']);}); $s->create('mod_radiussphere_identities',function($t){$t->increments('id');$t->integer('cluster_id')->unsigned();$t->string('username',253);$t->string('realm',253)->nullable();$t->string('state',20)->default('active');$t->timestamps();$t->unique(['cluster_id','username']);}); $s->create('mod_radiussphere_service_links',function($t){$t->increments('id');$t->integer('service_id')->unsigned()->unique();$t->integer('identity_id')->unsigned();$t->integer('policy_id')->unsigned();$t->integer('policy_revision')->unsigned();$t->timestamps();}); $s->create('mod_radiussphere_commands',function($t){$t->increments('id');$t->string('idempotency_key',100)->unique();$t->integer('cluster_id')->unsigned();$t->integer('service_id')->unsigned()->nullable();$t->string('type',50);$t->json('payload');$t->string('state',20)->default('pending');$t->integer('attempts')->unsigned()->default(0);$t->timestamp('available_at')->nullable();$t->text('last_error')->nullable();$t->timestamps();}); $s->create('mod_radiussphere_audit_events',function($t){$t->bigIncrements('id');$t->integer('admin_id')->unsigned()->nullable();$t->integer('client_id')->unsigned()->nullable();$t->string('action',100);$t->string('entity_type',50);$t->string('entity_id',100)->nullable();$t->json('metadata')->nullable();$t->string('correlation_id',64)->nullable();$t->timestamp('created_at')->useCurrent();}); } return ['status'=>'success','description'=>'RadiusSphere control-plane schema installed. Configure a cluster and policy before provisioning services.']; } catch(Throwable $e) { return ['status'=>'error','description'=>'RadiusSphere activation failed: '.$e->getMessage()]; } }
function radiussphere_deactivate(): array { return ['status'=>'info','description'=>'RadiusSphere was deactivated. Data was retained deliberately; remove mod_radiussphere_* tables manually only after export and retention review.']; }
function radiussphere_output(array $vars): void { $action=(string)($_GET['action']??'dashboard'); $link=$vars['modulelink']; $counts=['clusters'=>Capsule::table('mod_radiussphere_clusters')->count(),'policies'=>Capsule::table('mod_radiussphere_policies')->count(),'commands'=>Capsule::table('mod_radiussphere_commands')->whereIn('state',['pending','retry'])->count(),'failed'=>Capsule::table('mod_radiussphere_commands')->where('state','failed')->count()]; echo '<h2>RadiusSphere</h2><p>Enterprise FreeRADIUS control plane · v'.htmlspecialchars(RADIUSSPHERE_VERSION).'</p><p><a class="btn btn-default" href="'.$link.'">Dashboard</a> <a class="btn btn-default" href="'.$link.'&action=clusters">Clusters</a> <a class="btn btn-default" href="'.$link.'&action=policies">Policies</a> <a class="btn btn-default" href="'.$link.'&action=commands">Commands</a> <a class="btn btn-default" href="'.$link.'&action=audit">Audit</a></p>'; if($action==='dashboard'){echo '<div class="alert alert-info">Clusters: '.$counts['clusters'].' · Policies: '.$counts['policies'].' · Pending commands: '.$counts['commands'].' · Failed commands: '.$counts['failed'].'</div><p>Use this addon as the source of truth for clusters, policy revisions, identities, provisioning commands, and audit records. Backend drivers are introduced in the next implementation phase.</p>';return;} echo '<div class="alert alert-warning">The '.$action.' console is reserved by the installed schema. Its CRUD UI and driver actions are the next implementation increment; do not manipulate control-plane tables directly.</div>'; }
function radiussphere_audit(string $action,string $type,?string $id,array $metadata=[]): void { Capsule::table('mod_radiussphere_audit_events')->insert(['admin_id'=>isset($_SESSION['adminid'])?(int)$_SESSION['adminid']:null,'action'=>$action,'entity_type'=>$type,'entity_id'=>$id,'metadata'=>json_encode($metadata,JSON_THROW_ON_ERROR),'correlation_id'=>bin2hex(random_bytes(16)),'created_at'=>date('Y-m-d H:i:s')]); }
